### ISSUE TITLE
App Crashed 

### ISSUE THREAD

**Issue by Gagandeep1408** [DeepARSDK/videocall-android-java#14]
2022-11-15 13:01:20.644 27391-27391/ai.deepar.videocall E/AndroidRuntime: FATAL EXCEPTION: main
Process: ai.deepar.videocall, PID: 27391
java.nio.BufferOverflowException
at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
at java.nio.ByteBuffer.put(ByteBuffer.java:732)
at ai.deepar.videocall.MainActivity$3.analyze(MainActivity.java:260)
at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:370)
at androidx.camera.core.-$$Lambda$ImageAnalysis$qO2F3Tn7pfTvGyL-EvT8WWE0F0w.analyze(Unknown Source:4)
at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:121)
at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$g-dcm6aZmGod2IWKPwN4CArIZzI.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8163)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)

on All android versions it's not working. Kindly fix it ASAP.

**Comment by MateGasparini** [comment]
Hi @Gagandeep1408,

Thanks for reporting this issue.
We have pushed a fix in 4e9bbef6.

Please reopen if you're still experiencing the problem.
