### ISSUE TITLE
IndexOutOfBoundsException on starting the app

### ISSUE THREAD

**Issue by theGBguy** [DeepARSDK/videocall-android-java#16]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.deepar.videocall, PID: 8844
    java.lang.IndexOutOfBoundsException: off=460800, len=640 out of bounds (size=460800)
        at java.nio.Buffer.checkBounds(Buffer.java:587)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:233)
        at ai.deepar.videocall.MainActivity.lambda$bindImageAnalysis$2$MainActivity(MainActivity.java:277)
        at ai.deepar.videocall.-$$Lambda$MainActivity$6-rz8wA0IkEVJOBBUxw09mFTYGg.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:370)
        at androidx.camera.core.-$$Lambda$ImageAnalysis$qO2F3Tn7pfTvGyL-EvT8WWE0F0w.analyze(Unknown Source:4)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:121)
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$g-dcm6aZmGod2IWKPwN4CArIZzI.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetInternalformativ:5097 GL error 0x500 condition [!GLESv2Validation::internalFormatTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetInternalformativ:5097 GL error 0x500 condition [!GLESv2Validation::internalFormatTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGenerateMipmap:5142 GL error 0x502 condition [tex && !GLESv2Validation::unsizedFormat(internalformat) && !(GLESv2Validation::colorRenderableFormat(ctx, internalformat) && GLESv2Validation::filterableTexFormat(ctx, internalformat))]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetInternalformativ:5097 GL error 0x500 condition [!GLESv2Validation::internalFormatTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGenerateMipmap:5142 GL error 0x502 condition [tex && !GLESv2Validation::unsizedFormat(internalformat) && !(GLESv2Validation::colorRenderableFormat(ctx, internalformat) && GLESv2Validation::filterableTexFormat(ctx, internalformat))]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetInternalformativ:5097 GL error 0x500 condition [!GLESv2Validation::internalFormatTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGenerateMipmap:5142 GL error 0x502 condition [tex && !GLESv2Validation::unsizedFormat(internalformat) && !(GLESv2Validation::colorRenderableFormat(ctx, internalformat) && GLESv2Validation::filterableTexFormat(ctx, internalformat))]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetInternalformativ:5097 GL error 0x500 condition [!GLESv2Validation::internalFormatTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexImage2D:2611 GL error 0x500 condition [!GLESv2Validation::pixelFormat(ctx, format)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetInternalformativ:5097 GL error 0x500 condition [!GLESv2Validation::internalFormatTarget(ctx, target)]
E/EGL_emulation: tid 9001: eglCreateContext(1743): error 0x3005 (EGL_BAD_CONFIG)

```

**Comment by theGBguy** [comment]
maybe because I used an emulator 🥲
